# Generated by Django 3.2.7 on 2021-09-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='State',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
