# Generated by Django 3.2.7 on 2021-09-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherApp', '0003_searchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
