# Generated by Django 3.2.7 on 2021-09-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherApp', '0004_alter_searchhistory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='SearchDate',
            field=models.CharField(max_length=10),
        ),
    ]
