# Generated by Django 3.2.7 on 2021-09-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherApp', '0005_alter_searchhistory_searchdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='IsDay',
            field=models.BooleanField(default=False),
        ),
    ]
