# Generated by Django 3.2.7 on 2021-09-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherApp', '0006_searchhistory_isday'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='SearchTime',
            field=models.CharField(default='00:00', max_length=10),
            preserve_default=False,
        ),
    ]
